# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(829, 597)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.plot_frame = QtWidgets.QFrame(Form)
        self.plot_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plot_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plot_frame.setObjectName("plot_frame")
        self.gridLayout.addWidget(self.plot_frame, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TD_btn = QtWidgets.QPushButton(self.frame)
        self.TD_btn.setObjectName("TD_btn")
        self.gridLayout_2.addWidget(self.TD_btn, 3, 0, 1, 1)
        self.Plot_btn = QtWidgets.QPushButton(self.frame)
        self.Plot_btn.setObjectName("Plot_btn")
        self.gridLayout_2.addWidget(self.Plot_btn, 2, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Baseline_le = QtWidgets.QLineEdit(self.frame_3)
        self.Baseline_le.setObjectName("Baseline_le")
        self.gridLayout_3.addWidget(self.Baseline_le, 0, 0, 1, 1)
        self.Baseline_btn = QtWidgets.QPushButton(self.frame_3)
        self.Baseline_btn.setObjectName("Baseline_btn")
        self.gridLayout_3.addWidget(self.Baseline_btn, 0, 1, 1, 1)
        self.Response_le = QtWidgets.QLineEdit(self.frame_3)
        self.Response_le.setObjectName("Response_le")
        self.gridLayout_3.addWidget(self.Response_le, 1, 0, 1, 1)
        self.Response_btn = QtWidgets.QPushButton(self.frame_3)
        self.Response_btn.setObjectName("Response_btn")
        self.gridLayout_3.addWidget(self.Response_btn, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_3, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TD_btn.setText(_translate("Form", "3D Plot"))
        self.Plot_btn.setText(_translate("Form", "PLot"))
        self.Baseline_btn.setText(_translate("Form", "Base Line"))
        self.Response_btn.setText(_translate("Form", "Response"))

    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
